name: Test Apps Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v2

    - name: Restore nuget packages
      run: nuget restore SimpleLog.sln

    - name: Build Cpp x86
      working-directory: .
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=x86 TestCpp\TestCpp.vcxproj

    - name: Build Cpp x64
      working-directory: .
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=x64 TestCpp\TestCpp.vcxproj

    - name: Build CSharp
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore TestCSharp\TestCSharp.csproj

    - name: Build Test App
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore TestApp\TestApp.csproj

    - name: Run Test
      run: dotnet test --configuration ${{ matrix.configuration }} --no-restore --no-build .\TestApp\TestApp.csproj --logger trx --results-directory "TestResults-${{ matrix.configuration }}"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-${{ matrix.configuration }}
        path: TestResults-${{ matrix.configuration }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
